import ElectricBorder from "@/components/ElectricBorder";
import Galaxy from "@/components/Galaxy";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowRight, BrainCircuit, CheckCircle2, CircleAlert, ClipboardCheck, HeartPulse, Info, LoaderCircle, LockKeyhole, ShieldCheck, Sparkles, Stethoscope } from "lucide-react";
import { type FormEvent, useState } from "react";

type HeartForm = { age: number; sex: "M" | "F"; chestPainType: "ATA" | "NAP" | "ASY" | "TA"; restingBP: number; cholesterol: number; fastingBS: 0 | 1; restingECG: "Normal" | "ST" | "LVH"; maxHR: number; exerciseAngina: "Y" | "N"; oldpeak: number; stSlope: "Up" | "Flat" | "Down"; consentAcknowledged: boolean };
type HeartResult = { heartDiseaseProbability: number; confidence: number; signal: "Lower" | "Elevated"; summary: string; nextStep: string };

const initialForm: HeartForm = { age: 45, sex: "M", chestPainType: "ATA", restingBP: 120, cholesterol: 200, fastingBS: 0, restingECG: "Normal", maxHR: 150, exerciseAngina: "N", oldpeak: 1, stSlope: "Up", consentAcknowledged: false };
const signalClass = { Lower: "border-teal-300/35 bg-teal-300/10 text-teal-100", Elevated: "border-amber-300/35 bg-amber-300/10 text-amber-100" };

function SelectField<T extends string | number>({ label, value, items, onChange }: { label: string; value: T; items: readonly T[]; onChange: (value: T) => void }) {
  return <div className="space-y-2"><Label className="field-label">{label}</Label><Select value={String(value)} onValueChange={next => onChange((typeof value === "number" ? Number(next) : next) as T)}><SelectTrigger className="field-control"><SelectValue /></SelectTrigger><SelectContent className="border-white/10 bg-[#0c1822] text-white">{items.map(item => <SelectItem key={String(item)} value={String(item)}>{String(item)}</SelectItem>)}</SelectContent></Select></div>;
}

function NumberField({ label, value, min, max, step = 1, onChange }: { label: string; value: number; min: number; max: number; step?: number; onChange: (value: number) => void }) {
  return <div className="space-y-2"><Label className="field-label">{label}</Label><Input className="field-control" type="number" min={min} max={max} step={step} value={value} onChange={event => onChange(Number(event.target.value))} /></div>;
}

export default function Home() {
  const [form, setForm] = useState<HeartForm>(initialForm);
  const [result, setResult] = useState<HeartResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const utils = trpc.useUtils();
  const prediction = trpc.heartRisk.predict.useMutation({
    onSuccess: output => { setResult(output); setError(null); },
    onError: issue => setError(issue.message),
  });
  const update = <K extends keyof HeartForm>(key: K, value: HeartForm[K]) => setForm(current => ({ ...current, [key]: value }));
  const submit = (event: FormEvent) => { event.preventDefault(); setError(null); prediction.mutate({ ...form, consentAcknowledged: form.consentAcknowledged as true }); };

  return <main className="relative min-h-screen overflow-hidden bg-[#06131a] text-white"><Galaxy density={0.55} hueShift={168} glowIntensity={0.32} saturation={0.42} speed={0.26} twinkleIntensity={0.14} rotationSpeed={0.012} />
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_14%_10%,rgba(26,117,126,0.22),transparent_30%),radial-gradient(circle_at_92%_6%,rgba(27,81,142,0.16),transparent_28%),linear-gradient(180deg,rgba(6,19,26,.25),#06131a_70%)]" />
    <section className="relative mx-auto flex min-h-[700px] max-w-7xl flex-col px-5 pb-20 pt-6 sm:px-8 lg:px-12"><nav className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-xl border border-teal-100/15 bg-teal-300/10"><HeartPulse className="size-4 text-teal-100" /></div><span className="font-display text-base font-medium tracking-[0.22em]">CARDIA</span></div><Badge className="border border-teal-200/15 bg-[#0b2027]/75 px-3 py-1 text-[10px] font-medium tracking-[0.17em] text-teal-50/75 hover:bg-[#0b2027]/75"><LockKeyhole className="mr-1.5 size-3" /> PRIVATE SCREENING DEMO</Badge></nav>
      <div className="grid flex-1 items-center gap-12 py-20 lg:grid-cols-[1.25fr_.75fr] lg:py-28"><div className="max-w-3xl"><div className="eyebrow"><span className="h-px w-10 bg-teal-200/60" /> Decision support, not diagnosis</div><h1 className="mt-7 font-display text-5xl leading-[.98] tracking-[-.055em] sm:text-7xl lg:text-[5.7rem]">A clearer view<br />of <span className="text-transparent bg-clip-text bg-gradient-to-r from-teal-100 via-white to-sky-200">cardiac signals.</span></h1><p className="mt-8 max-w-xl text-base leading-7 text-white/64 sm:text-lg">A careful model interface for translating structured screening inputs into an interpretable, clinician-first discussion prompt.</p><div className="mt-10 flex flex-wrap gap-3"><a href="#screen"><Button className="rounded-full bg-teal-100 px-6 font-semibold text-[#06222a] hover:bg-white">Run a screening <ArrowRight className="ml-2 size-4" /></Button></a><a href="#method" className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/[.035] px-5 text-sm text-white/75 transition-colors hover:bg-white/[.08]"><Info className="size-3.5 text-teal-100" />How to interpret this</a></div><p className="mt-6 flex items-center gap-2 text-xs text-white/42"><ShieldCheck className="size-3.5 text-teal-200" />No names, contact details, or identifiers are requested.</p></div>
        <div className="glass-card rounded-[2rem] p-7 sm:p-8"><div className="flex items-center justify-between"><span className="text-xs font-medium uppercase tracking-[.18em] text-white/55">Model operating posture</span><Activity className="size-4 text-teal-100" /></div><div className="mt-9 flex items-end justify-between"><div><p className="text-5xl font-medium tracking-[-.05em]">11</p><p className="mt-2 max-w-[15rem] text-sm leading-6 text-white/50">Structured clinical features supplied to a server-side Logistic Regression model.</p></div><div className="grid size-16 place-items-center rounded-2xl border border-teal-200/15 bg-teal-300/10"><BrainCircuit className="size-6 text-teal-100" /></div></div><div className="mt-9 grid grid-cols-3 gap-2 border-t border-white/10 pt-5 text-center text-[10px] uppercase tracking-[.13em]"><span className="rounded-full border border-teal-200/20 bg-teal-200/10 py-2 text-teal-100">Validated</span><span className="rounded-full border border-sky-200/20 bg-sky-200/10 py-2 text-sky-100">Private</span><span className="rounded-full border border-white/15 bg-white/[.04] py-2 text-white/65">Persisted</span></div></div>
      </div></section>
    <section id="screen" className="relative mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-12"><div className="eyebrow"><Sparkles className="size-3.5" /> Structured screening</div><div className="mt-5 grid gap-7 lg:grid-cols-[1fr_.54fr]"><form onSubmit={submit} className="glass-card rounded-[2rem] p-5 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div><h2 className="font-display text-3xl tracking-[-.04em]">Build the profile</h2><p className="mt-2 max-w-lg text-sm leading-6 text-white/52">Use representative, non-identifying data for this demo. The model expects the same eleven fields used in its training pipeline.</p></div><Badge className="border border-teal-100/15 bg-teal-300/10 px-3 py-1.5 text-xs text-teal-50 hover:bg-teal-300/10"><Stethoscope className="mr-1.5 size-3.5" />Screening model</Badge></div>
      <fieldset className="form-section"><legend>Basic profile</legend><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><NumberField label="Age (years)" value={form.age} min={18} max={120} onChange={value => update("age", value)} /><SelectField label="Recorded sex" value={form.sex} items={["M", "F"] as const} onChange={value => update("sex", value)} /><SelectField label="Chest pain type" value={form.chestPainType} items={["ATA", "NAP", "ASY", "TA"] as const} onChange={value => update("chestPainType", value)} /></div></fieldset>
      <fieldset className="form-section"><legend>Measurements</legend><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><NumberField label="Resting BP (mm Hg)" value={form.restingBP} min={50} max={300} onChange={value => update("restingBP", value)} /><NumberField label="Cholesterol (mg/dL)" value={form.cholesterol} min={0} max={1000} onChange={value => update("cholesterol", value)} /><SelectField label="Fasting blood sugar" value={form.fastingBS} items={[0, 1] as const} onChange={value => update("fastingBS", value)} /><SelectField label="Resting ECG" value={form.restingECG} items={["Normal", "ST", "LVH"] as const} onChange={value => update("restingECG", value)} /><NumberField label="Maximum heart rate" value={form.maxHR} min={30} max={260} onChange={value => update("maxHR", value)} /><NumberField label="ST depression (Oldpeak)" value={form.oldpeak} min={-10} max={15} step={0.1} onChange={value => update("oldpeak", value)} /></div></fieldset>
      <fieldset className="form-section"><legend>Exercise and ECG response</legend><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><SelectField label="Exercise angina" value={form.exerciseAngina} items={["Y", "N"] as const} onChange={value => update("exerciseAngina", value)} /><SelectField label="ST slope" value={form.stSlope} items={["Up", "Flat", "Down"] as const} onChange={value => update("stSlope", value)} /></div></fieldset>
      <div className="mt-8 rounded-2xl border border-teal-100/10 bg-teal-200/[.045] p-4"><div className="flex items-start gap-3"><Checkbox id="consent" checked={form.consentAcknowledged} onCheckedChange={checked => update("consentAcknowledged", checked === true)} className="mt-0.5 border-white/30" /><div><Label htmlFor="consent" className="cursor-pointer text-sm font-medium text-white/86">I understand this is an educational screening demo, not a medical diagnosis.</Label><p className="mt-1 text-xs leading-5 text-white/48">I will not enter personal identifiers, and I understand that results must be interpreted by a qualified clinician.</p></div></div></div>
      {error && <p className="mt-5 rounded-xl border border-rose-300/25 bg-rose-400/10 p-3 text-sm text-rose-100">{error}</p>}<div className="mt-7 flex flex-wrap items-center justify-between gap-4 border-t border-white/10 pt-6"><p className="max-w-sm text-xs leading-5 text-white/42">Requests are validated server-side, protected by a basic abuse throttle, and persisted without identifying fields.</p><Button type="submit" disabled={!form.consentAcknowledged || prediction.isPending} className="rounded-full bg-teal-100 px-6 font-semibold text-[#06222a] hover:bg-white">{prediction.isPending ? <><LoaderCircle className="mr-2 size-4 animate-spin" />Analyzing inputs</> : <>Analyze profile <ArrowRight className="ml-2 size-4" /></>}</Button></div></form><ResultPanel result={result} pending={prediction.isPending} /></div></section>
    <section id="method" className="relative mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-12"><div className="grid gap-7 lg:grid-cols-[.68fr_1.32fr]"><div><div className="eyebrow"><ClipboardCheck className="size-3.5" /> Transparent by design</div><h2 className="mt-5 font-display text-4xl tracking-[-.045em]">A model should earn its place in the conversation.</h2><p className="mt-5 max-w-md text-sm leading-7 text-white/58">Cardia presents a model signal, not a clinical conclusion. The application does not collect identity, contact, or location data in this screening flow.</p></div><div className="grid gap-4 sm:grid-cols-3"><InfoCard icon={<ShieldCheck />} title="Bounded inputs" copy="Ranges and category values are checked before inference begins." /><InfoCard icon={<LockKeyhole />} title="Minimal data" copy="Only model fields and an acknowledgement are recorded for the demo history." /><InfoCard icon={<CircleAlert />} title="Clinical handoff" copy="Positive model signals explicitly direct users to qualified clinical assessment." /></div></div></section>
    <section className="relative mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-12"><div className="glass-card rounded-[2rem] p-6 sm:p-8"><div className="grid gap-8 md:grid-cols-[1.05fr_.95fr]"><div><div className="eyebrow"><LockKeyhole className="size-3.5" /> Data boundary</div><h2 className="mt-5 font-display text-3xl tracking-[-.04em]">Sensitive screening history is never displayed publicly.</h2><p className="mt-4 max-w-xl text-sm leading-7 text-white/58">Acknowledged model events are persisted for this demo without direct identifiers. Access to detailed historical records is restricted to an authenticated administrator workflow rather than exposed to every visitor.</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-teal-100/10 bg-teal-200/[.04] p-5"><ShieldCheck className="size-5 text-teal-100" /><p className="mt-5 text-sm font-semibold">Validated before inference</p><p className="mt-2 text-xs leading-5 text-white/48">Input bounds, required acknowledgement, and a request throttle are enforced by the server.</p></div><div className="rounded-2xl border border-teal-100/10 bg-teal-200/[.04] p-5"><LockKeyhole className="size-5 text-teal-100" /><p className="mt-5 text-sm font-semibold">Restricted history access</p><p className="mt-2 text-xs leading-5 text-white/48">Detailed historic events are available only through protected administrative procedures.</p></div></div></div></div></section>
    <footer className="relative border-t border-white/[.08] px-5 py-8 text-center text-xs leading-6 tracking-[.12em] text-white/38">CARDIA · EDUCATIONAL HEART-RISK SCREENING DEMO · NOT FOR DIAGNOSIS OR EMERGENCY DECISIONS</footer>
  </main>;
}

function ResultPanel({ result, pending }: { result: HeartResult | null; pending: boolean }) {
  const probability = result ? Math.round(result.heartDiseaseProbability * 100) : 0; const confidence = result ? Math.round(result.confidence * 100) : 0;
  return <ElectricBorder color={result?.signal === "Elevated" ? "#f5b95c" : "#54d8c2"} className="self-start rounded-[2rem]"><aside className="glass-card flex min-h-[460px] flex-col rounded-[2rem] p-6 sm:p-8"><div className="flex items-center justify-between"><span className="text-xs font-medium uppercase tracking-[.18em] text-white/55">Model signal</span><HeartPulse className="size-4 text-teal-100" /></div>{pending ? <div className="flex flex-1 flex-col items-center justify-center text-center"><LoaderCircle className="size-8 animate-spin text-teal-100" /><p className="mt-5 text-sm text-white/58">Processing the screening pattern…</p></div> : result ? <div className="flex flex-1 flex-col"><div className="mt-9 flex items-end justify-between gap-4"><div><p className="text-sm text-white/55">Positive-class probability</p><div className="mt-1 font-display text-7xl tracking-[-.075em]">{probability}<span className="text-3xl text-white/45">%</span></div></div><Badge className={`rounded-full border px-3 py-1.5 text-xs ${signalClass[result.signal]}`}>{result.signal} signal</Badge></div><div className="mt-8"><div className="mb-2 flex justify-between text-xs text-white/48"><span>Model confidence</span><span>{confidence}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-teal-300 to-sky-200 transition-all duration-700" style={{ width: `${confidence}%` }} /></div></div><p className="mt-8 text-sm leading-6 text-white/76">{result.summary}</p><div className="mt-5 rounded-2xl border border-white/10 bg-white/[.045] p-4"><p className="text-xs font-semibold uppercase tracking-[.15em] text-teal-100">Important context</p><p className="mt-2 text-sm leading-6 text-white/62">{result.nextStep}</p></div></div> : <div className="flex flex-1 flex-col justify-center"><div className="grid size-12 place-items-center rounded-2xl border border-teal-100/15 bg-teal-200/10"><BrainCircuit className="size-5 text-teal-100" /></div><h3 className="mt-6 font-display text-3xl tracking-[-.04em]">Awaiting a profile.</h3><p className="mt-3 max-w-sm text-sm leading-6 text-white/55">A model probability, signal label, and safe next-step message will appear after the input is acknowledged and analyzed.</p><p className="mt-7 flex items-center gap-2 text-xs text-white/40"><CheckCircle2 className="size-4 text-teal-100" />Server-side model evaluation</p></div>}</aside></ElectricBorder>;
}

function InfoCard({ icon, title, copy }: { icon: React.ReactNode; title: string; copy: string }) { return <div className="glass-card rounded-2xl p-5"><div className="text-teal-100">{icon}</div><h3 className="mt-6 text-sm font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-white/52">{copy}</p></div>; }
