import Galaxy from "@/components/Galaxy";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowUpRight, CalendarDays, Clock3, History, LoaderCircle, MoonStar, Orbit, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { FormEvent, useState } from "react";

type BookingForm = {
  hotel: "City Hotel" | "Resort Hotel"; leadTime: number; arrivalYear: number; arrivalMonth: "January" | "February" | "March" | "April" | "May" | "June" | "July" | "August" | "September" | "October" | "November" | "December"; arrivalWeek: number; arrivalDay: number; weekendNights: number; weekNights: number; adults: number; children: number; babies: number; meal: "BB" | "HB" | "FB" | "SC" | "Undefined"; country: string; marketSegment: "Direct" | "Corporate" | "Online TA" | "Offline TA/TO" | "Complementary" | "Groups" | "Aviation"; distributionChannel: "Direct" | "Corporate" | "TA/TO" | "GDS"; repeatedGuest: boolean; previousCancellations: number; previousBookingsNotCanceled: number; reservedRoomType: string; assignedRoomType: string; bookingChanges: number; depositType: "No Deposit" | "Non Refund" | "Refundable"; customerType: "Transient" | "Transient-Party" | "Contract" | "Group"; averageDailyRate: number; parkingSpaces: number; specialRequests: number; waitingListDays: number;
};

const initialForm: BookingForm = { hotel: "City Hotel", leadTime: 30, arrivalYear: 2017, arrivalMonth: "June", arrivalWeek: 25, arrivalDay: 15, weekendNights: 1, weekNights: 2, adults: 2, children: 0, babies: 0, meal: "BB", country: "PRT", marketSegment: "Online TA", distributionChannel: "TA/TO", repeatedGuest: false, previousCancellations: 0, previousBookingsNotCanceled: 0, reservedRoomType: "A", assignedRoomType: "A", bookingChanges: 0, depositType: "No Deposit", customerType: "Transient", averageDailyRate: 100, parkingSpaces: 0, specialRequests: 1, waitingListDays: 0 };
const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"] as const;
const riskTone = { Low: "border-emerald-300/35 bg-emerald-300/10 text-emerald-200", Medium: "border-amber-300/35 bg-amber-300/10 text-amber-100", High: "border-rose-300/35 bg-rose-300/10 text-rose-100" };

function SelectField<T extends string>({ label, value, items, onChange }: { label: string; value: T; items: readonly T[]; onChange: (value: T) => void }) {
  return <div className="space-y-2"><Label className="field-label">{label}</Label><Select value={value} onValueChange={onChange}><SelectTrigger className="field-control"><SelectValue /></SelectTrigger><SelectContent className="border-white/10 bg-[#121124] text-white">{items.map(item => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></div>;
}

function NumberField({ label, value, min = 0, max, step = 1, onChange }: { label: string; value: number; min?: number; max?: number; step?: number; onChange: (value: number) => void }) {
  return <div className="space-y-2"><Label className="field-label">{label}</Label><Input className="field-control" type="number" min={min} max={max} step={step} value={value} onChange={event => onChange(Number(event.target.value))} /></div>;
}

export default function Home() {
  const [form, setForm] = useState<BookingForm>(initialForm);
  const [result, setResult] = useState<ReturnType<typeof predictionSnapshot> | null>(null);
  const [error, setError] = useState<string | null>(null);
  const utils = trpc.useUtils();
  const history = trpc.prediction.history.useQuery({ limit: 8 });
  const prediction = trpc.prediction.predict.useMutation({ onSuccess: output => { setResult(predictionSnapshot(output)); setError(null); utils.prediction.history.invalidate(); }, onError: issue => setError(issue.message) });
  const update = <K extends keyof BookingForm>(key: K, value: BookingForm[K]) => setForm(current => ({ ...current, [key]: value }));
  const submit = (event: FormEvent) => { event.preventDefault(); prediction.mutate({ ...form, country: form.country.toUpperCase() }); };

  return <main className="relative min-h-screen overflow-hidden bg-[#070711] text-white"><Galaxy />
    <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_12%_0%,rgba(86,64,204,0.18),transparent_31%),radial-gradient(circle_at_87%_20%,rgba(17,137,219,0.12),transparent_26%),linear-gradient(180deg,rgba(7,7,17,0.08),#070711_62%)]" />
    <section className="relative mx-auto flex min-h-[650px] max-w-7xl flex-col px-5 pb-20 pt-6 sm:px-8 lg:px-12">
      <nav className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-full border border-white/20 bg-white/10 backdrop-blur"><Orbit className="size-4 text-violet-200" /></div><span className="font-display text-sm font-semibold tracking-[0.24em] text-white/90">STAYSIGHT</span></div><Badge className="border border-white/10 bg-white/5 px-3 py-1 text-[10px] font-medium tracking-[0.18em] text-white/65 hover:bg-white/5">INFERENCE CONSOLE <span className="ml-2 inline-block size-1.5 rounded-full bg-emerald-300 shadow-[0_0_12px_#86efac]" /></Badge></nav>
      <div className="grid flex-1 items-center gap-12 py-20 lg:grid-cols-[1.25fr_0.75fr] lg:py-28"><div className="max-w-3xl"><div className="mb-7 flex items-center gap-3 text-xs font-medium uppercase tracking-[0.22em] text-violet-200/80"><span className="h-px w-9 bg-violet-300/65" />Booking intelligence, tuned for certainty</div><h1 className="font-display text-5xl font-medium leading-[0.98] tracking-[-0.055em] text-white sm:text-7xl lg:text-[5.7rem]">Reservations,<br /><span className="text-transparent bg-clip-text bg-gradient-to-r from-violet-200 via-white to-sky-200">read in starlight.</span></h1><p className="mt-8 max-w-xl text-base leading-7 text-white/62 sm:text-lg">Transform booking signals into a measured cancellation forecast—before an empty room becomes a missed opportunity.</p><div className="mt-10 flex flex-wrap gap-3"><a href="#analyze"><Button className="rounded-full bg-white px-6 text-sm font-semibold text-[#0a0913] hover:bg-violet-100">Analyze a reservation <ArrowUpRight className="ml-2 size-4" /></Button></a><a href="#history" className="inline-flex items-center rounded-full border border-white/15 bg-white/[0.035] px-6 text-sm font-medium text-white/80 transition-colors hover:bg-white/10">View prediction log</a></div></div>
        <div className="glass-panel relative overflow-hidden rounded-[2rem] p-6 sm:p-8"><div className="absolute -right-14 -top-14 size-44 rounded-full bg-violet-500/25 blur-3xl" /><div className="relative"><div className="flex items-center justify-between"><span className="text-xs font-medium uppercase tracking-[0.18em] text-white/55">Live prediction posture</span><Activity className="size-4 text-violet-200" /></div><div className="mt-9"><div className="text-5xl font-medium tracking-[-0.05em] text-white">3 tiers</div><p className="mt-2 max-w-xs text-sm leading-6 text-white/55">A calibrated reading across Low, Medium, and High cancellation risk.</p></div><div className="mt-9 space-y-3"><div className="h-px bg-white/10" /><div className="grid grid-cols-3 gap-2 text-center text-[10px] uppercase tracking-[0.13em]"><span className="rounded-full border border-emerald-300/25 bg-emerald-300/10 py-2 text-emerald-200">Low</span><span className="rounded-full border border-amber-300/25 bg-amber-300/10 py-2 text-amber-100">Medium</span><span className="rounded-full border border-rose-300/25 bg-rose-300/10 py-2 text-rose-100">High</span></div></div></div></div></div>
    </section>
    <section id="analyze" className="relative mx-auto max-w-7xl px-5 pb-20 sm:px-8 lg:px-12"><div className="section-kicker"><Sparkles className="size-3.5" /> Reservation analysis</div><div className="mt-5 grid gap-7 lg:grid-cols-[1fr_0.55fr]"><form onSubmit={submit} className="glass-panel rounded-[2rem] p-5 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-display text-3xl tracking-[-0.04em]">Map the booking</h2><p className="mt-2 text-sm text-white/50">Every field mirrors the production model contract.</p></div><div className="flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-xs text-white/55"><ShieldCheck className="size-3.5 text-violet-200" />Server-side inference</div></div>
      <fieldset className="mt-8 border-t border-white/10 pt-6"><legend className="pr-3 text-xs font-medium uppercase tracking-[0.18em] text-violet-200/80">Booking window</legend><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><SelectField label="Hotel" value={form.hotel} items={["City Hotel", "Resort Hotel"] as const} onChange={value => update("hotel", value)} /><NumberField label="Lead time (days)" value={form.leadTime} max={730} onChange={value => update("leadTime", value)} /><SelectField label="Arrival month" value={form.arrivalMonth} items={months} onChange={value => update("arrivalMonth", value)} /><NumberField label="Arrival year" value={form.arrivalYear} min={2015} max={2017} onChange={value => update("arrivalYear", value)} /><NumberField label="Arrival week" value={form.arrivalWeek} min={1} max={53} onChange={value => update("arrivalWeek", value)} /><NumberField label="Arrival day" value={form.arrivalDay} min={1} max={31} onChange={value => update("arrivalDay", value)} /></div></fieldset>
      <fieldset className="mt-8 border-t border-white/10 pt-6"><legend className="pr-3 text-xs font-medium uppercase tracking-[0.18em] text-violet-200/80">Stay and guests</legend><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><NumberField label="Weekend nights" value={form.weekendNights} max={60} onChange={value => update("weekendNights", value)} /><NumberField label="Week nights" value={form.weekNights} max={60} onChange={value => update("weekNights", value)} /><NumberField label="Adults" value={form.adults} min={1} max={20} onChange={value => update("adults", value)} /><NumberField label="Children" value={form.children} max={20} onChange={value => update("children", value)} /><NumberField label="Babies" value={form.babies} max={10} onChange={value => update("babies", value)} /><SelectField label="Meal plan" value={form.meal} items={["BB", "HB", "FB", "SC", "Undefined"] as const} onChange={value => update("meal", value)} /></div></fieldset>
      <fieldset className="mt-8 border-t border-white/10 pt-6"><legend className="pr-3 text-xs font-medium uppercase tracking-[0.18em] text-violet-200/80">Channel and guest profile</legend><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div className="space-y-2"><Label className="field-label">Country code</Label><Input className="field-control uppercase" maxLength={3} value={form.country} onChange={event => update("country", event.target.value.toUpperCase())} /></div><SelectField label="Market segment" value={form.marketSegment} items={["Direct", "Corporate", "Online TA", "Offline TA/TO", "Complementary", "Groups", "Aviation"] as const} onChange={value => update("marketSegment", value)} /><SelectField label="Booking channel" value={form.distributionChannel} items={["Direct", "Corporate", "TA/TO", "GDS"] as const} onChange={value => update("distributionChannel", value)} /><SelectField label="Deposit type" value={form.depositType} items={["No Deposit", "Non Refund", "Refundable"] as const} onChange={value => update("depositType", value)} /><SelectField label="Customer type" value={form.customerType} items={["Transient", "Transient-Party", "Contract", "Group"] as const} onChange={value => update("customerType", value)} /><div className="flex items-end pb-3"><div className="flex items-center gap-3"><Checkbox id="repeated" checked={form.repeatedGuest} onCheckedChange={value => update("repeatedGuest", value === true)} /><Label htmlFor="repeated" className="text-sm text-white/75">Repeated guest</Label></div></div></div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><NumberField label="Previous cancellations" value={form.previousCancellations} max={100} onChange={value => update("previousCancellations", value)} /><NumberField label="Previous confirmed stays" value={form.previousBookingsNotCanceled} max={1000} onChange={value => update("previousBookingsNotCanceled", value)} /><NumberField label="Booking changes" value={form.bookingChanges} max={100} onChange={value => update("bookingChanges", value)} /></div></fieldset>
      <fieldset className="mt-8 border-t border-white/10 pt-6"><legend className="pr-3 text-xs font-medium uppercase tracking-[0.18em] text-violet-200/80">Room and preferences</legend><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><SelectField label="Reserved room" value={form.reservedRoomType} items={["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L"] as const} onChange={value => update("reservedRoomType", value)} /><SelectField label="Assigned room" value={form.assignedRoomType} items={["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P"] as const} onChange={value => update("assignedRoomType", value)} /><NumberField label="Average daily rate" value={form.averageDailyRate} max={100000} step={0.01} onChange={value => update("averageDailyRate", value)} /><NumberField label="Parking spaces" value={form.parkingSpaces} max={5} onChange={value => update("parkingSpaces", value)} /><NumberField label="Special requests" value={form.specialRequests} max={5} onChange={value => update("specialRequests", value)} /><NumberField label="Waiting list days" value={form.waitingListDays} max={1000} onChange={value => update("waitingListDays", value)} /></div></fieldset>
      {error && <p className="mt-6 rounded-xl border border-rose-300/25 bg-rose-400/10 p-3 text-sm text-rose-100">{error}</p>}<div className="mt-8 flex flex-wrap items-center justify-between gap-4 border-t border-white/10 pt-6"><p className="max-w-sm text-xs leading-5 text-white/40">This forecast is an operational signal, not a guarantee. Predictions are saved to the secure history log.</p><Button type="submit" disabled={prediction.isPending} className="rounded-full bg-violet-300 px-6 text-[#130d25] hover:bg-violet-200">{prediction.isPending ? <><LoaderCircle className="mr-2 size-4 animate-spin" />Reading reservation</> : <>Analyze reservation <ArrowUpRight className="ml-2 size-4" /></>}</Button></div></form>
      <ResultPanel result={result} pending={prediction.isPending} /></div></section>
    <section id="history" className="relative mx-auto max-w-7xl px-5 pb-24 sm:px-8 lg:px-12"><div className="section-kicker"><History className="size-3.5" /> Persistent history</div><div className="glass-panel mt-5 overflow-hidden rounded-[2rem]"><div className="flex items-center justify-between border-b border-white/10 p-6 sm:px-8"><div><h2 className="font-display text-2xl tracking-[-0.03em]">Prediction log</h2><p className="mt-1 text-sm text-white/50">Your most recent model readings, stored beyond this browser session.</p></div><div className="hidden rounded-full border border-white/10 px-3 py-1 text-xs text-white/45 sm:block">{history.data?.length ?? 0} saved</div></div><div className="overflow-x-auto"><table className="w-full min-w-[710px] text-left"><thead className="bg-white/[0.025] text-[10px] uppercase tracking-[0.14em] text-white/42"><tr><th className="px-6 py-4 sm:px-8">Recorded</th><th className="px-6 py-4">Booking</th><th className="px-6 py-4">Guests / stay</th><th className="px-6 py-4">Probability</th><th className="px-6 py-4 sm:px-8">Risk</th></tr></thead><tbody>{history.isLoading ? <tr><td colSpan={5} className="px-8 py-10 text-sm text-white/45">Loading saved signals…</td></tr> : history.data?.length ? history.data.map(item => <HistoryRow key={item.id} item={item} />) : <tr><td colSpan={5} className="px-8 py-12 text-center text-sm text-white/45">The constellation is clear. Your next completed prediction will be saved here.</td></tr>}</tbody></table></div></div></section>
    <footer className="relative border-t border-white/[0.08] px-5 py-7 text-center text-xs tracking-[0.16em] text-white/35">STAYSIGHT · HOTEL CANCELLATION INTELLIGENCE</footer>
  </main>;
}

function predictionSnapshot(value: { cancellationProbability: number; confidence: number; riskLabel: "Low" | "Medium" | "High"; recommendation: string }) { return value; }

function ResultPanel({ result, pending }: { result: ReturnType<typeof predictionSnapshot> | null; pending: boolean }) {
  const probability = result ? Math.round(result.cancellationProbability * 100) : 0; const confidence = result ? Math.round(result.confidence * 100) : 0;
  return <aside className="glass-panel flex min-h-[420px] flex-col rounded-[2rem] p-6 sm:p-8"><div className="flex items-center justify-between"><span className="text-xs font-medium uppercase tracking-[0.18em] text-white/55">Cancellation outlook</span><MoonStar className="size-4 text-violet-200" /></div>{pending ? <div className="flex flex-1 flex-col items-center justify-center text-center"><LoaderCircle className="size-8 animate-spin text-violet-200" /><p className="mt-5 text-sm text-white/60">Aligning booking signals with the model…</p></div> : result ? <div className="flex flex-1 flex-col"><div className="mt-9 flex items-end justify-between gap-5"><div><p className="text-sm text-white/55">Cancellation probability</p><div className="mt-1 font-display text-7xl tracking-[-0.07em]">{probability}<span className="text-3xl text-white/50">%</span></div></div><Badge className={`rounded-full border px-3 py-1.5 text-xs ${riskTone[result.riskLabel]}`}>{result.riskLabel} risk</Badge></div><div className="mt-8"><div className="mb-2 flex items-center justify-between text-xs text-white/50"><span>Model confidence</span><span>{confidence}%</span></div><div className="h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-violet-400 to-sky-300 transition-all duration-700" style={{ width: `${confidence}%` }} /></div></div><div className="mt-8 rounded-2xl border border-white/10 bg-white/[0.045] p-5"><p className="text-xs font-medium uppercase tracking-[0.16em] text-violet-200/85">Recommended next move</p><p className="mt-3 text-sm leading-6 text-white/68">{result.recommendation}</p></div><p className="mt-auto pt-8 text-xs leading-5 text-white/38">The exact prediction, confidence, and booking data were saved in the log below.</p></div> : <div className="flex flex-1 flex-col justify-center"><div className="grid size-12 place-items-center rounded-2xl border border-white/10 bg-white/[0.04]"><Activity className="size-5 text-violet-200" /></div><h3 className="mt-6 font-display text-3xl tracking-[-0.04em]">Awaiting a signal.</h3><p className="mt-3 max-w-sm text-sm leading-6 text-white/55">Complete the reservation form to receive a probability, confidence level, and clear operational recommendation.</p><div className="mt-8 flex items-center gap-3 text-xs text-white/42"><CalendarDays className="size-4" />Supports the supplied 2015–2017 booking model range</div></div>}</aside>;
}

function HistoryRow({ item }: { item: { id: number; bookingDetails: unknown; cancellationProbability: number; riskLabel: "Low" | "Medium" | "High"; createdAt: Date } }) {
  const booking = item.bookingDetails as Partial<BookingForm>; const guests = (booking.adults ?? 0) + (booking.children ?? 0) + (booking.babies ?? 0); const nights = (booking.weekendNights ?? 0) + (booking.weekNights ?? 0);
  return <tr className="border-t border-white/[0.07] text-sm text-white/70"><td className="px-6 py-4 sm:px-8"><div className="flex items-center gap-2 text-white/50"><Clock3 className="size-3.5" />{new Date(item.createdAt).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" })}</div></td><td className="px-6 py-4"><span className="font-medium text-white/85">{booking.hotel ?? "Hotel"}</span><span className="ml-2 text-xs text-white/38">{booking.marketSegment ?? ""}</span></td><td className="px-6 py-4"><span className="inline-flex items-center gap-1.5"><UsersRound className="size-3.5 text-violet-200" />{guests} guest{guests === 1 ? "" : "s"}</span><span className="ml-3 text-white/38">{nights} night{nights === 1 ? "" : "s"}</span></td><td className="px-6 py-4 font-medium text-white">{Math.round(item.cancellationProbability * 100)}%</td><td className="px-6 py-4 sm:px-8"><Badge className={`rounded-full border px-2.5 py-1 text-[11px] ${riskTone[item.riskLabel]}`}>{item.riskLabel}</Badge></td></tr>;
}
